### 建立報名
# @name last_id
POST http://localhost:3001/api/signup
Content-Type: application/json

{
  "name": "新同學",
  "email": "new@example.com",
  "phone": "0911222333"
}

### 取得清單
GET http://localhost:3001/api/signup

### 更新
PATCH http://localhost:3001/api/signup/{{last_id.response.body.id}}
Content-Type: application/json

{
  "phone": "0912345678"
}
### 刪除 
DELETE http://localhost:3001/api/signup/{{{{last_id.response.body.id}}}}